"""create_candidates_table

Revision ID: 8ad9bbe9b0ac
Revises: 7600d2f53813
Create Date: 2026-04-27 02:29:16.087622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad9bbe9b0ac'
down_revision: Union[str, Sequence[str], None] = '7600d2f53813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.String(length=2000), nullable=False),
    sa.Column('education', sa.String(length=500), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SCREENING', 'INTERVIEW', 'HIRED', 'REJECTED', name='candidatestatus'), nullable=False),
    sa.Column('resume_file_path', sa.String(length=500), nullable=False),
    sa.Column('status_note', sa.String(length=1000), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
