"""make jd_id nullable, add candidate_id and results_json to match_sessions

Revision ID: cdcedf23b8d4
Revises: 233fe68a051b
Create Date: 2026-04-27 04:07:42.878327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdcedf23b8d4'
down_revision: Union[str, Sequence[str], None] = '233fe68a051b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('results_json', sa.Text(), nullable=True))
        batch_op.alter_column('jd_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_match_sessions_candidate_id'), ['candidate_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_sessions_candidate_id'))
        batch_op.alter_column('jd_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('results_json')
        batch_op.drop_column('candidate_id')

    # ### end Alembic commands ###
